name = "granite-cloud"
main = "src/index.ts"
compatibility_date = "2026-03-31"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "VAULT_BUCKET"
bucket_name = "granite-vaults"

[[d1_databases]]
binding = "DB"
database_name = "granite-index"
database_id = ""
